#:kivy 1.0

#:import MDRaisedButton kivymd.button.MDRaisedButton
#:import MDCard kivymd.card.MDCard
#:import MDTextField kivymd.textfields.MDTextField
#:import MDIconButton kivymd.button.MDIconButton
#:import md_icons kivymd.icon_definitions.md_icons
#:import MDLabel kivymd.label.MDLabel


<MyFirstWidget>:
  spacing: 50
  padding:[50,50,50,50]
  MDCard:
    StackLayout:
      padding:[16,16,16,16]
      anchor_y:'top'
      MDTextField:
        id:txtbx
        hint:'test'
        multiline:True
      MDIconButton:
        icon:'send'
        on_press: app.snack(txtbx.text)












